# -*- coding: utf-8 -*-
"""datamining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2uVYxwpGekusJW38wI9ae5zXkEgromJ
"""

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/My Drive/Colab Notebooks/credito/"

# importing python's libs (importing numpy and matplot aren't necessary in google colab)

import pandas as pd
import numpy as np
import matplotlib as plt


df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/credito/Training50.csv")

df.head(10)

df.columns

# Mostra principais estatísticas descritivas dos dados, como a contagem (count), média (mean), desvio padrão (std), mínimo (min), quartis (25%, 50% e 75%) e o máximo (max)
df.describe()

# conta quantos trabalhadores são estrangeiros (id 1, 482) e quantos não são (id 2, 17)
df['Foreign.Worker'].value_counts()

# Distribuição das variáveis: histograma de crédito (x) por quantidade de ids (y)
df['Credit.Amount'].hist(bins=50)

# Distribuição das variáveis: boxplot de valores extremos de crédito, outliers
df.boxplot(column='Credit.Amount')

# Distribuição das variáveis: boxplot de disparidade de ativos disponíveis mais valiosos (disparidades sociais demandam segregação de informação)
df.boxplot(column='Most.valuable.available.asset')

df.boxplot(column ='Credit.Amount', by = 'Most.valuable.available.asset')