# -*- coding: utf-8 -*-
"""datascience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BERhtcDBWZZyjsJZQpQhFOhSyGxg_J4g
"""

# Cria lista de usuários com os campos id e nome
usuarios = [
    {"id": 0, "nome": "Hero"},
    {"id": 1, "nome": "Dunn"},
    {"id": 2, "nome": "Sue"},
    {"id": 3, "nome": "Chi"},
    {"id": 4, "nome": "Thor"},
    {"id": 5, "nome": "Clive"},
    {"id": 6, "nome": "Hicks"},
    {"id": 7, "nome": "Devin"},
    {"id": 8, "nome": "Kate"},
    {"id": 9, "nome": "Klein"}
]

usuarios

# Cria uma lista com as conexões entre ids (usuários)
pares_de_amizade = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4), (4, 5), (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)]

pares_de_amizade

amigos = {usuario["id"]: [] for usuario in usuarios}
amigos

# Preenche lista onde a posição é um id (usuário) e seus valores listam os ids (usuários) com os quais se conecta
for i, j in pares_de_amizade:
  amigos[i].append(j)
  amigos[j].append(i)

amigos

# Total de conexões entre id (usuários)
def numero_de_amigos(usuario):
  usuario_id = usuario["id"]
  amigo_ids = amigos[usuario_id]
  return len(amigo_ids)

total_conexoes = sum(numero_de_amigos(usuario) for usuario in usuarios)

total_conexoes

# Média de conexões por id (usuários)
num_usuarios = len(usuarios)
avg_connections = total_conexoes / num_usuarios

avg_connections

# Lista quantidade de conexões por id (usuários)
num_amigos_por_id = [(usuario["id"], numero_de_amigos(usuario)) for usuario in usuarios]
num_amigos_por_id

# Organiza por id (usuários) com mais conexões
num_amigos_por_id.sort(
    key=lambda id_e_amigos: id_e_amigos[1],

    reverse=True
)

num_amigos_por_id

